In [2]:
import nltk
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import string
import sys
import os
import pandas as pd
import numpy as np

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/kamakshibansal/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [470]:
df = pd.DataFrame({'A': [["word","delivery"], ["word","word"], ["cat"], ["cat","delivery","word"]]})

In [471]:
df

                       A
0       [word, delivery]
1           [word, word]
2                  [cat]
3  [cat, delivery, word]

In [227]:
df.to_csv("p.csv")

In [276]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
df = df.join(pd.DataFrame(mlb.fit_transform(df.pop('A')),
                          columns=mlb.classes_,
                          index=df.index))

In [277]:
df

   cat  delivery  word
0    0         1     1
1    0         0     1
2    1         0     0
3    1         1     1

In [469]:
df2 = pd.DataFrame({'A': [['word,delivery'], ['word,word'], ['cat'], ['cat,delivery,word']]})

In [247]:
df2

                     A
0      [word,delivery]
1          [word,word]
2                [cat]
3  [cat,delivery,word]

In [253]:
for i, val in enumerate (df2["A"]):
    df2[i]= (', '.join('"' + item + '"' for item in val))

# (', '.join('"' + item + '"' for item in df2["A"]))

In [254]:
df2["A"].to_csv("k.csv")

In [242]:
def comma_separator(df2.A):
    """The function comma_separator takes a list and joins it
       into a string with (", ") and adds " and " before the last value."""

    if type(someList) is list and bool(someList) is True:
        return ", ".join(someList[:-1]) + " and " + someList[-1]

SyntaxError: invalid syntax (<ipython-input-242-f68c32973e11>, line 1)

In [281]:
MReport1= pd.read_csv("/Users/kamakshibansal/Downloads/MReport1.csv")
MReport2= pd.read_csv("/Users/kamakshibansal/Downloads/MReport2.csv")
MReport3= pd.read_csv("/Users/kamakshibansal/Downloads/MReport3.csv")
MReport4= pd.read_csv("/Users/kamakshibansal/Downloads/MReport4.csv")
MReport5= pd.read_csv("/Users/kamakshibansal/Downloads/MReport5.csv")

In [282]:
MReport1.feedback = MReport1.feedback.replace('\s+', ' ', regex=True)
MReport2.feedback = MReport2.feedback.replace('\s+', ' ', regex=True)
MReport3.feedback = MReport3.feedback.replace('\s+', ' ', regex=True)
MReport4.feedback = MReport4.feedback.replace('\s+', ' ', regex=True)
MReport5.feedback = MReport5.feedback.replace('\s+', ' ', regex=True)

In [283]:
MReport11 = pd.DataFrame()
MReport11["feedback"]= MReport1["feedback"]
MReport11["category"]= MReport1["Answer2_1"]


MReport22 = pd.DataFrame()
MReport22["feedback"]= MReport2["feedback"]
MReport22["category"]= MReport2["Answer2_1"]


MReport33 = pd.DataFrame()
MReport33["feedback"]= MReport3["feedback"]
MReport33["category"]= MReport3["Answer2_1"]


MReport44 = pd.DataFrame()
MReport44["feedback"]= MReport4["feedback"]
MReport44["category"]= MReport4["Answer2_1"]


MReport55 = pd.DataFrame()
MReport55["feedback"]= MReport5["feedback"]
MReport55["category"]= MReport5["Answer2_1"]


New_MReport=pd.concat([MReport11,MReport22, MReport33, MReport44, MReport55])
# New_MReport.to_csv("Category_MReport.csv")

In [307]:
New_MReport.head(5)

,feedback,category
0,Fast Delivery. Always before time. Thanks,Delivery speed:[Delivery]
1,I have order brown shoe .And I got olive green...,Received wrong product:[Wrong product]
2,The delivery was quick and the person who hand...,"Delivery speed:[Delivery],Delivery boy behavio..."
3,Delivery is on expected date and that what I l...,"Delivery speed:[Delivery],Card payment on deli..."
4,Delivery guy is a decent nd friendly guy,Delivery boy behaviour:[Delivery]

In [472]:
df_Mreport = pd.DataFrame(New_MReport.category.str.split(',',2).tolist(),
                                   columns = ['col1','col2', "col3"])

In [342]:
df_Mreport.to_csv("Category_MReport.csv")

In [473]:
df_Mreport.head(10)

,col1,col2,col3
0,Delivery speed:[Delivery],None,None
1,Received wrong product:[Wrong product],None,None
2,Delivery speed:[Delivery],Delivery boy behaviour:[Delivery],None
3,Delivery speed:[Delivery],Card payment on delivery:[Delivery],None
4,Delivery boy behaviour:[Delivery],None,None
5,Product quality:[Quality],None,None
6,Quality of packaging:[Quality],Product quality:[Quality],None
7,Quality of packaging:[Quality],None,None
8,Delivery speed:[Delivery],None,None
9,Delivery speed:[Delivery],None,None

In [474]:
df_Mreport["col1"] = df_Mreport['col1'].str.extract("\[(.*)\]") 
df_Mreport["col2"] = df_Mreport['col2'].str.extract("\[(.*)\]") 
df_Mreport["col3"] = df_Mreport['col3'].str.extract("\[(.*)\]") 


# pd.DataFrame(df_Mreport.col1.str.split('[',2).tolist(),columns = ['col1','col4'])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  This is separate from the ipykernel package so we can avoid doing imports until

In [475]:
df_Mreport.head(10)

            col1      col2 col3
0       Delivery       NaN  NaN
1  Wrong product       NaN  NaN
2       Delivery  Delivery  NaN
3       Delivery  Delivery  NaN
4       Delivery       NaN  NaN
5        Quality       NaN  NaN
6        Quality   Quality  NaN
7        Quality       NaN  NaN
8       Delivery       NaN  NaN
9       Delivery       NaN  NaN

In [476]:
df_Mreport.update("'" + df_Mreport[['col1']].astype(str) + "'")

In [477]:
for i, val in enumerate(df_Mreport["col2"]):
    if (pd.notnull(df_Mreport.at[i,'col2'])):
        df_Mreport.at[i,'col2']="'" + df_Mreport.at[i,'col2'] + "'"
        
for j, val in enumerate(df_Mreport["col3"]):
    if (pd.notnull(df_Mreport.at[j,'col3'])):
        df_Mreport.at[j,'col3']="'" + df_Mreport.at[j,'col3'] + "'"

In [478]:
df_Mreport.head(10)

              col1        col2 col3
0       'Delivery'         NaN  NaN
1  'Wrong product'         NaN  NaN
2       'Delivery'  'Delivery'  NaN
3       'Delivery'  'Delivery'  NaN
4       'Delivery'         NaN  NaN
5        'Quality'         NaN  NaN
6        'Quality'   'Quality'  NaN
7        'Quality'         NaN  NaN
8       'Delivery'         NaN  NaN
9       'Delivery'         NaN  NaN

In [479]:
New = pd.DataFrame()
New["feedback"]= New_MReport["feedback"]
New["col1"]= df_Mreport["col1"]
New["col2"]= df_Mreport["col2"]
New["col3"]= df_Mreport["col3"]
New.head(10)

,feedback,col1,col2,col3
0,Fast Delivery. Always before time. Thanks,'Delivery',NaN,NaN
1,I have order brown shoe .And I got olive green...,'Wrong product',NaN,NaN
2,The delivery was quick and the person who hand...,'Delivery','Delivery',NaN
3,Delivery is on expected date and that what I l...,'Delivery','Delivery',NaN
4,Delivery guy is a decent nd friendly guy,'Delivery',NaN,NaN
5,Its really good .. my daughter loves it,'Quality',NaN,NaN
6,It's very good Packing condition some times.qu...,'Quality','Quality',NaN
7,One t shirt was fully crushed rest everything ...,'Quality',NaN,NaN
8,Great. Delivered with in 13 hours,'Delivery',NaN,NaN
9,Superfast delivery! I'm impressed.,'Delivery',NaN,NaN

In [125]:
# New["category"] = New[New.columns[1:]].apply(lambda x: ','.join(x.dropna().astype(int).astype(str)),axis=1)

In [480]:
New["category"]  = New[['col1', 'col2', 'col3']].apply(lambda x: ','.join(x.fillna('').map(str)), axis=1)
New["category"] = New["category"] .str.strip(',')

In [481]:
New.head(5)

,feedback,col1,col2,col3,category
0,Fast Delivery. Always before time. Thanks,'Delivery',NaN,NaN,'Delivery'
1,I have order brown shoe .And I got olive green...,'Wrong product',NaN,NaN,'Wrong product'
2,The delivery was quick and the person who hand...,'Delivery','Delivery',NaN,"'Delivery','Delivery'"
3,Delivery is on expected date and that what I l...,'Delivery','Delivery',NaN,"'Delivery','Delivery'"
4,Delivery guy is a decent nd friendly guy,'Delivery',NaN,NaN,'Delivery'

In [482]:
New= New.drop(['col1','col2','col3'], axis=1)

In [483]:
New.head(10)

                                            feedback               category
0          Fast Delivery. Always before time. Thanks             'Delivery'
1  I have order brown shoe .And I got olive green...        'Wrong product'
2  The delivery was quick and the person who hand...  'Delivery','Delivery'
3  Delivery is on expected date and that what I l...  'Delivery','Delivery'
4           Delivery guy is a decent nd friendly guy             'Delivery'
5            Its really good .. my daughter loves it              'Quality'
6  It's very good Packing condition some times.qu...    'Quality','Quality'
7  One t shirt was fully crushed rest everything ...              'Quality'
8                  Great. Delivered with in 13 hours             'Delivery'
9                 Superfast delivery! I'm impressed.             'Delivery'

In [152]:
New.to_csv("Comma_sep_category_mission.csv")

In [416]:
Dictionary1= pd.read_csv("/Users/kamakshibansal/dictionary.csv")
File1= pd.read_csv("/Users/kamakshibansal/Downloads/File1.csv")
File2= pd.read_csv("/Users/kamakshibansal/Downloads/File2.csv")
File3= pd.read_csv("/Users/kamakshibansal/Downloads/File3.csv")

In [417]:
Dictionary1.feedback = Dictionary1.feedback.replace('\s+', ' ', regex=True)
File1.feedback = File1.feedback.replace('\s+', ' ', regex=True)
File2.feedback = File2.feedback.replace('\s+', ' ', regex=True)
File3.feedback = File3.feedback.replace('\s+', ' ', regex=True)

In [418]:
Filedict = pd.DataFrame()
Filedict["feedback"]= Dictionary1["feedback"]
Filedict["category"]= Dictionary1["category"]

File11 = pd.DataFrame()
File11["feedback"]= File1["feedback"]
File11["category"]= File1["Category"]


File22 = pd.DataFrame()
File22["feedback"]= File2["feedback"]
File22["category"]= File2["Category"]

File33 = pd.DataFrame()
File33["feedback"]= File3["feedback"]
File33["category"]= File3["Category"]

New_Dict=pd.concat([Filedict, File11,File22, File33])

In [419]:
New_Dict.head(5)

                                            feedback  category
0  I got my order vey fast,the day after i placed...  Category
1                                  XXX is amazing...   General
2                          The delivery was on time.  Delivery
3  I m really happy with this early delivery and ...  Category
4  Early morning... Ordered at night and next day...  Delivery

In [420]:
New_Dict.update("'" + New_Dict[['category']].astype(str) + "'")

In [484]:
Train=pd.concat([New_Dict,New])
Train.to_csv("Train_category.csv")

In [485]:
Train.head(2)

                                            feedback    category
0  I got my order vey fast,the day after i placed...  'Category'
1                                  XXX is amazing...   'General'

In [428]:
# Train['category'] = Train[['category']].values.tolist()

In [487]:
Train.update("[" + Train[['category']].astype(str) + "]")

In [488]:
Train['category']

0                  ['Category']
1                   ['General']
2                  ['Delivery']
3                  ['Category']
4                  ['Delivery']
5                  ['Delivery']
6                  ['Delivery']
7                  ['Delivery']
8                  ['Delivery']
9                  ['Delivery']
10                 ['Delivery']
11                 ['Delivery']
12                 ['Delivery']
13                 ['Delivery']
14                 ['Delivery']
15                 ['Category']
16                 ['Delivery']
17                 ['Delivery']
18                 ['Delivery']
19                ['Warehouse']
20                 ['Delivery']
21                 ['Delivery']
22                 ['Delivery']
23                  ['Catalog']
24                 ['Category']
25                 ['Category']
26                 ['Delivery']
27                 ['Delivery']
28                 ['Delivery']
29                  ['General']
                 ...
2056               ['Delivery']
2057               ['Delivery']
2058               ['Delivery']
2059               ['Delivery']
2060                ['General']
2061               ['Delivery']
2062                ['Quality']
2063               ['Delivery']
2064               ['Delivery']
2065               ['Delivery']
2066               ['Delivery']
2067    ['Delivery','Delivery']
2068               ['Delivery']
2069                ['Quality']
2070                ['General']
2071               ['Delivery']
2072                ['Details']
2073               ['Delivery']
2074      ['Quality','Details']
2075                ['Details']
2076                ['General']
2077                ['General']
2078                ['General']
2079               ['Delivery']
2080               ['Delivery']
2081     ['Quality','Delivery']
2082               ['Delivery']
2083    ['Delivery','Delivery']
2084    ['Delivery','Delivery']
2085               ['Delivery']
Name: category, Length: 154862, dtype: object

In [489]:
# Fit = pd.DataFrame()
# Fit["category"]= Train['category']

In [490]:
# Fit

In [467]:
# from sklearn.preprocessing import MultiLabelBinarizer

# mlb = MultiLabelBinarizer()
# Fit = Fit.join(pd.DataFrame(mlb.fit_transform(Fit.pop('category')),
#                           columns=mlb.classes_,
#                           index=Fit.index))

In [433]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
Train = Train.join(pd.DataFrame(mlb.fit_transform(Train.pop('category')),
                          columns=mlb.classes_,
                          index=Train.index))

In [432]:
Train.to_csv("ff.csv")

In [434]:
Train.shape

(551828, 41)

In [436]:
Train

,feedback,,',+,",",-,/,A,C,D,...,m,n,o,p,r,s,t,u,v,y
0,"I got my order vey fast,the day after i placed...",0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
0,"I got my order vey fast,the day after i placed...",0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,"I got my order vey fast,the day after i placed...",0,1,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
0,"I got my order vey fast,the day after i placed...",0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
0,"I got my order vey fast,the day after i placed...",0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,"I got my order vey fast,the day after i placed...",0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,"I got my order vey fast,the day after i placed...",0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,"I got my order vey fast,the day after i placed...",0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,"I got my order vey fast,the day after i placed...",0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Delivery associate was very soft spoken ??,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
0,Delivery associate was very soft spoken ??,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Delivery associate was very soft spoken ??,0,1,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
0,Delivery associate was very soft spoken ??,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
0,Delivery associate was very soft spoken ??,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Delivery associate was very soft spoken ??,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Delivery associate was very soft spoken ??,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Delivery associate was very soft spoken ??,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Delivery associate was very soft spoken ??,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Really inspired by your vision donating clothe...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
0,Really inspired by your vision donating clothe...,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Really inspired by your vision donating clothe...,0,1,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
0,Really inspired by your vision donating clothe...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
0,Really inspired by your vision donating clothe...,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Really inspired by your vision donating clothe...,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Really inspired by your vision donating clothe...,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Really inspired by your vision donating clothe...,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Really inspired by your vision donating clothe...,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Awesome dress. Size is perfect. I m very happy...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
0,Awesome dress. Size is perfect. I m very happy...,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
0,Awesome dress. Size is perfect. I m very happy...,0,1,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103260,more varieties on lower price ranges,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,1,1,0
103261,Plz check the products before sending. The ano...,0,1,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,0,0
103262,Great price great product,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,1,1,0
103263,There is issues with size and when i choosing ...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
103264,I ordered 1 size more than my size is 10.i don...,0,1,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,0,0
103265,Stitches arent up to the mark. On the very fir...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
103266,No complaints at all. Worth money ?? product.,0,1,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,0,0
103267,Product looked like used and cover and packing...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
103268,Very good quality and fitting!!,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
103269,improve quality of the product and material/size,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
103270,"Bhosdiwalo, daam kam rakho aise chutiya cheezo...",0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,1,1,0
103271,Properly mention the size cloth quality,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
103272,Thank u for giving us best style on lower budg...,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,1,1,0
103273,product not as in the shown in the site. color...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
103274,Product shown in the image are not actual as r...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
103275,XXXis able to deliver quality products at comp...,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,1,1,0
103276,You guys 1stly check the product before delive...,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
103277,This product is stitched in with wrong detaili...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
103278,This items fabric should be much better and si...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
103279,Kindly check the products before sending to co...,1,1,0,0,0,0,0,0,0,...,0,0,1,0,1,1,1,0,1,0
103280,Sell branded products they are worth it love s...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
103281,Material and stitching of T shirt is good and ...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
103282,The material could be little more better and t...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,1
103283,Please send display items..I have received two...,0,1,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,1,0,0
103284,I totally like the product. It was exactly wha...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
103285,Some products of some brands are not upto the ...,0,1,0,0,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
103286,Decent delivery. Great discounts.,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
103287,Value for money quick delivery. Thank you Myntra,0,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
103288,Expecting the same experience in future both i...,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
103289,We try to return the product the application p...,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [231]:
t= pd.read_csv("/Users/kamakshibansal/t.csv")

In [303]:
o= pd.read_csv("/Users/kamakshibansal/t.csv")

In [304]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
t = t.join(pd.DataFrame(mlb.fit_transform(t.pop('category')),
                          columns=mlb.classes_,
                          index=t.index))

In [305]:
t.shape

(154862, 42)

In [437]:
Train.to_csv("G.csv")